name: Workflow Demo

on:
  workflow_dispatch:
    inputs:
      texto:
        description: 'Introduce un texto'
        required: true
        default: ''

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Texto introducido
        run: echo "El texto introducido es  ${{ github.event.inputs.texto }}!"
